### PR TITLE
Fix bill short title encoding issues

### PR DESCRIPTION
**Pull request by king-millez**
In this PR I've fixed the short title encoding issues that reared their ugly heads in DigiPol.

In loving memory of �€™

### CODE REVIEW

**Comment by connorhsm** [comment]
Is there a reason why we're not using regex to remove characters that are not alphanumeric and valid white spaces?

**Comment by king-millez** [comment]
> Is there a reason why we're not using regex to remove characters that are not alphanumeric or valid white spaces?

Personally it's because I haven't learnt how to use regex properly yet, plus this works, so make of that what you will.

**Review by connorhsm — DISMISSED** [review]
Okay, that can be done another time.

**Comment by connorhsm** [comment]
@KipCrossing Could you please investigate why CircleCI is stuck?

**Comment by KipCrossing** [comment]
Screenshot from 2020-10-25 22-03-05

@connorhsm found it. I thought it would be in the circleci.yml file but it's in the GUI. May have to push a new commit to run it @king-millez

**Comment by KipCrossing** [comment]
Also, feel free to use regular expressions. Using `.replace()` was just a quick fix that blew out of hand

**Comment by KipCrossing** [comment]
Screenshot from 2020-10-25 22-13-40

@king-millez magic commit, lol

**Comment by king-millez** [comment]
Nice, everything working now?

**Review by connorhsm — APPROVED** [review]

**Pull request merged**
