### PR TITLE
Add VIC Parliament

### PR DESCRIPTION
**Pull request by king-millez**
Will (maybe) be eased as of 11:59PM

### CODE REVIEW

**Comment by KipCrossing** [comment]
Nice work!

**Comment by KipCrossing** [comment]
1) Merge the latest master
2) change version to 0.8 in setup (will push to PyPI)

**Review by connorhsm — COMMENTED** [review]
This PR shouldn't make any changes to other parliaments.

**Comment by king-millez** [comment]
Removed the changes I made to other parliaments @connorhsm

**Review by connorhsm — APPROVED** [review]
Thanks, in future we should look at reversing the previous commit and recommitting without the unrelated changes, instead of adding further unnecessary commits.

Otherwise, looks good to me.

**Comment by KipCrossing** [comment]
Deploy should fail as there is no new tag

**Pull request merged**
